### ISSUE TITLE
Qemu

### ISSUE THREAD

**Issue by NathanMcMillan54** [NathanMcMillan54/FOMOSv2-CL#7]
There needs to be a simple shellscript file that runs FOMOS in Qemu for developers.

**Comment by dragonkey100** [comment]
How are you running it now?

**Comment by NathanMcMillan54** [comment]
> How are you running it now?

I know it's a bad thing to do but right now there is no way of running/testing it. For now I just write code that might work until there is an easy way of running this.

**Comment by NathanMcMillan54** [comment]
Added ``qemu.sh``. Arguments are, ``arm`` and ``x86``.
